require( 'sinatra' )
require( 'sinatra/contrib/all' )
require( 'pry' )
require_relative( '../models/book.rb' )
require_relative( '../models/publisher.rb' )
require_relative( '../models/author.rb' )
also_reload( '../models/*' )
